//! Simple-font character encodings (fonts.md §2 "Character-code
//! interpretation").
//!
//! Maps a single-byte code to a Unicode scalar so the outline engine's cmap
//! can find the glyph. WinAnsiEncoding is implemented exactly (cp1252);
//! StandardEncoding and MacRomanEncoding are handled for their Latin range with
//! a latin-1 high-byte approximation (full Adobe tables are a later refinement).
//! `/Differences` glyph names resolve through a compact AGL subset plus the
//! algorithmic `uniXXXX` form.

/// A named base encoding from a font's `/Encoding`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BaseEncoding {
    Standard,
    WinAnsi,
    MacRoman,
    /// MacExpertEncoding (Annex D.4): small caps, oldstyle figures,
    /// superiors/inferiors, fractions and ligatures. Name-only — its glyphs
    /// have expert names, not Unicode identities.
    MacExpert,
    /// No named encoding — use the font's built-in cmap with the raw code
    /// (symbolic fonts).
    Symbolic,
    /// The Symbol face's built-in encoding (Annex D.5).
    SymbolFont,
    /// The ZapfDingbats face's built-in encoding (Annex D.6).
    ZapfDingbats,
}

/// The cp1252 replacements for the `0x80..=0x9F` block; `\0` marks undefined.
const CP1252_HIGH: [char; 32] = [
    '\u{20AC}', '\0', '\u{201A}', '\u{0192}', '\u{201E}', '\u{2026}', '\u{2020}', '\u{2021}',
    '\u{02C6}', '\u{2030}', '\u{0160}', '\u{2039}', '\u{0152}', '\0', '\u{017D}', '\0', '\0',
    '\u{2018}', '\u{2019}', '\u{201C}', '\u{201D}', '\u{2022}', '\u{2013}', '\u{2014}', '\u{02DC}',
    '\u{2122}', '\u{0161}', '\u{203A}', '\u{0153}', '\0', '\u{017E}', '\u{0178}',
];

impl BaseEncoding {
    pub fn from_name(name: &[u8]) -> Option<BaseEncoding> {
        match name {
            b"WinAnsiEncoding" => Some(BaseEncoding::WinAnsi),
            b"StandardEncoding" => Some(BaseEncoding::Standard),
            b"MacRomanEncoding" => Some(BaseEncoding::MacRoman),
            b"MacExpertEncoding" => Some(BaseEncoding::MacExpert),
            _ => None,
        }
    }

    /// The Unicode scalar for `code`, or `None` if undefined in this encoding.
    pub fn to_char(self, code: u8) -> Option<char> {
        match self {
            BaseEncoding::Symbolic => None,
            BaseEncoding::WinAnsi => match code {
                0x20..=0x7E => Some(code as char),
                0x80..=0x9F => {
                    let c = CP1252_HIGH[(code - 0x80) as usize];
                    (c != '\0').then_some(c)
                }
                0xA0..=0xFF => char::from_u32(code as u32),
                _ => None,
            },
            // Standard: ASCII with two typographic swaps; high bytes are the
            // Adobe standard set (approximated as undefined here).
            BaseEncoding::Standard => match code {
                0x27 => Some('\u{2019}'), // quoteright
                0x60 => Some('\u{2018}'), // quoteleft
                0x20..=0x7E => Some(code as char),
                _ => None,
            },
            // MacRoman: ASCII exact; high bytes from the real Mac OS Roman
            // table (PDFium `UnicodeFromAppleRomanCharCode` analog) — the
            // former latin-1 approximation mis-mapped every 0x80–0xFF code.
            BaseEncoding::MacRoman => match code {
                0x20..=0x7E => Some(code as char),
                0x80..=0xFF => Some(MACROMAN_HIGH[(code - 0x80) as usize]),
                _ => None,
            },
            // Expert glyphs (oldstyle figures, small caps, superiors) have
            // *names*, not usable Unicode identities; resolution is by name
            // via `builtin_glyph_name`, matching PDFium (whose MacExpert
            // Unicode table is zeros outside a few slots).
            BaseEncoding::MacExpert => None,
            // The two symbolic standard faces carry their own code tables.
            BaseEncoding::SymbolFont => table_char(&SYMBOL_ENCODING, code),
            BaseEncoding::ZapfDingbats => table_char(&ZAPF_ENCODING, code),
        }
    }
}

/// Glyph names of MacExpertEncoding (Annex D.4), indexed from character
/// code 32. Ported verbatim from PDFium's `kMacExpertEncodingNames`
/// (`cpdf_fontencoding.cpp`).
pub const MACEXPERT_NAMES: [Option<&[u8]>; 224] = [
    Some(b"space"),
    Some(b"exclamsmall"),
    Some(b"Hungarumlautsmall"),
    Some(b"centoldstyle"),
    Some(b"dollaroldstyle"),
    Some(b"dollarsuperior"),
    Some(b"ampersandsmall"),
    Some(b"Acutesmall"),
    Some(b"parenleftsuperior"),
    Some(b"parenrightsuperior"),
    Some(b"twodotenleader"),
    Some(b"onedotenleader"),
    Some(b"comma"),
    Some(b"hyphen"),
    Some(b"period"),
    Some(b"fraction"),
    Some(b"zerooldstyle"),
    Some(b"oneoldstyle"),
    Some(b"twooldstyle"),
    Some(b"threeoldstyle"),
    Some(b"fouroldstyle"),
    Some(b"fiveoldstyle"),
    Some(b"sixoldstyle"),
    Some(b"sevenoldstyle"),
    Some(b"eightoldstyle"),
    Some(b"nineoldstyle"),
    Some(b"colon"),
    Some(b"semicolon"),
    None,
    Some(b"threequartersemdash"),
    None,
    Some(b"questionsmall"),
    None,
    None,
    None,
    None,
    Some(b"Ethsmall"),
    None,
    None,
    Some(b"onequarter"),
    Some(b"onehalf"),
    Some(b"threequarters"),
    Some(b"oneeighth"),
    Some(b"threeeighths"),
    Some(b"fiveeighths"),
    Some(b"seveneighths"),
    Some(b"onethird"),
    Some(b"twothirds"),
    None,
    None,
    None,
    None,
    None,
    None,
    Some(b"ff"),
    Some(b"fi"),
    Some(b"fl"),
    Some(b"ffi"),
    Some(b"ffl"),
    Some(b"parenleftinferior"),
    None,
    Some(b"parenrightinferior"),
    Some(b"Circumflexsmall"),
    Some(b"hypheninferior"),
    Some(b"Gravesmall"),
    Some(b"Asmall"),
    Some(b"Bsmall"),
    Some(b"Csmall"),
    Some(b"Dsmall"),
    Some(b"Esmall"),
    Some(b"Fsmall"),
    Some(b"Gsmall"),
    Some(b"Hsmall"),
    Some(b"Ismall"),
    Some(b"Jsmall"),
    Some(b"Ksmall"),
    Some(b"Lsmall"),
    Some(b"Msmall"),
    Some(b"Nsmall"),
    Some(b"Osmall"),
    Some(b"Psmall"),
    Some(b"Qsmall"),
    Some(b"Rsmall"),
    Some(b"Ssmall"),
    Some(b"Tsmall"),
    Some(b"Usmall"),
    Some(b"Vsmall"),
    Some(b"Wsmall"),
    Some(b"Xsmall"),
    Some(b"Ysmall"),
    Some(b"Zsmall"),
    Some(b"colonmonetary"),
    Some(b"onefitted"),
    Some(b"rupiah"),
    Some(b"Tildesmall"),
    None,
    None,
    Some(b"asuperior"),
    Some(b"centsuperior"),
    None,
    None,
    None,
    None,
    Some(b"Aacutesmall"),
    Some(b"Agravesmall"),
    Some(b"Acircumflexsmall"),
    Some(b"Adieresissmall"),
    Some(b"Atildesmall"),
    Some(b"Aringsmall"),
    Some(b"Ccedillasmall"),
    Some(b"Eacutesmall"),
    Some(b"Egravesmall"),
    Some(b"Ecircumflexsmall"),
    Some(b"Edieresissmall"),
    Some(b"Iacutesmall"),
    Some(b"Igravesmall"),
    Some(b"Icircumflexsmall"),
    Some(b"Idieresissmall"),
    Some(b"Ntildesmall"),
    Some(b"Oacutesmall"),
    Some(b"Ogravesmall"),
    Some(b"Ocircumflexsmall"),
    Some(b"Odieresissmall"),
    Some(b"Otildesmall"),
    Some(b"Uacutesmall"),
    Some(b"Ugravesmall"),
    Some(b"Ucircumflexsmall"),
    Some(b"Udieresissmall"),
    None,
    Some(b"eightsuperior"),
    Some(b"fourinferior"),
    Some(b"threeinferior"),
    Some(b"sixinferior"),
    Some(b"eightinferior"),
    Some(b"seveninferior"),
    Some(b"Scaronsmall"),
    None,
    Some(b"centinferior"),
    Some(b"twoinferior"),
    None,
    Some(b"Dieresissmall"),
    None,
    Some(b"Caronsmall"),
    Some(b"Scaronsmall"),
    Some(b"fiveinferior"),
    None,
    Some(b"commainferior"),
    Some(b"periodinferior"),
    Some(b"Yacutesmall"),
    None,
    Some(b"dollarinferior"),
    None,
    None,
    Some(b"Thornsmall"),
    None,
    Some(b"nineinferior"),
    Some(b"zeroinferior"),
    Some(b"Zcaronsmall"),
    Some(b"AEsmall"),
    Some(b"Oslashsmall"),
    Some(b"questiondownsmall"),
    Some(b"oneinferior"),
    Some(b"asuperior"),
    None,
    None,
    None,
    None,
    None,
    None,
    Some(b"Cedillasmall"),
    None,
    None,
    None,
    None,
    None,
    Some(b"OEsmall"),
    Some(b"figuredash"),
    Some(b"hyphensuperior"),
    None,
    None,
    None,
    None,
    Some(b"exclamdownsmall"),
    None,
    Some(b"Ydieresissmall"),
    None,
    Some(b"onesuperior"),
    Some(b"twosuperior"),
    Some(b"threesuperior"),
    Some(b"foursuperior"),
    Some(b"fivesuperior"),
    Some(b"sixsuperior"),
    Some(b"sevensuperior"),
    Some(b"ninesuperior"),
    Some(b"zerosuperior"),
    None,
    Some(b"esuperior"),
    Some(b"rsuperior"),
    None,
    None,
    None,
    Some(b"isuperior"),
    Some(b"ssuperior"),
    Some(b"dsuperior"),
    None,
    None,
    None,
    None,
    None,
    Some(b"lsuperior"),
    Some(b"Ogoneksmall"),
    Some(b"Brevesmall"),
    Some(b"Macronsmall"),
    Some(b"bsuperior"),
    Some(b"nsuperior"),
    Some(b"msuperior"),
    Some(b"commasuperior"),
    Some(b"periodsuperior"),
    Some(b"Dotaccentsmall"),
    Some(b"Ringsmall"),
    None,
    None,
    None,
    None,
];

/// Mac OS Roman, codes 0x80–0xFF → Unicode (the standard Apple table;
/// PDFium `UnicodeFromAppleRomanCharCode`). ASCII 0x20–0x7E is identity.
const MACROMAN_HIGH: [char; 128] = [
    '\u{00C4}', '\u{00C5}', '\u{00C7}', '\u{00C9}', '\u{00D1}', '\u{00D6}', '\u{00DC}', '\u{00E1}',
    '\u{00E0}', '\u{00E2}', '\u{00E4}', '\u{00E3}', '\u{00E5}', '\u{00E7}', '\u{00E9}', '\u{00E8}',
    '\u{00EA}', '\u{00EB}', '\u{00ED}', '\u{00EC}', '\u{00EE}', '\u{00EF}', '\u{00F1}', '\u{00F3}',
    '\u{00F2}', '\u{00F4}', '\u{00F6}', '\u{00F5}', '\u{00FA}', '\u{00F9}', '\u{00FB}', '\u{00FC}',
    '\u{2020}', '\u{00B0}', '\u{00A2}', '\u{00A3}', '\u{00A7}', '\u{2022}', '\u{00B6}', '\u{00DF}',
    '\u{00AE}', '\u{00A9}', '\u{2122}', '\u{00B4}', '\u{00A8}', '\u{2260}', '\u{00C6}', '\u{00D8}',
    '\u{221E}', '\u{00B1}', '\u{2264}', '\u{2265}', '\u{00A5}', '\u{00B5}', '\u{2202}', '\u{2211}',
    '\u{220F}', '\u{03C0}', '\u{222B}', '\u{00AA}', '\u{00BA}', '\u{03A9}', '\u{00E6}', '\u{00F8}',
    '\u{00BF}', '\u{00A1}', '\u{00AC}', '\u{221A}', '\u{0192}', '\u{2248}', '\u{2206}', '\u{00AB}',
    '\u{00BB}', '\u{2026}', '\u{00A0}', '\u{00C0}', '\u{00C3}', '\u{00D5}', '\u{0152}', '\u{0153}',
    '\u{2013}', '\u{2014}', '\u{201C}', '\u{201D}', '\u{2018}', '\u{2019}', '\u{00F7}', '\u{25CA}',
    '\u{00FF}', '\u{0178}', '\u{2044}', '\u{20AC}', '\u{2039}', '\u{203A}', '\u{FB01}', '\u{FB02}',
    '\u{2021}', '\u{00B7}', '\u{201A}', '\u{201E}', '\u{2030}', '\u{00C2}', '\u{00CA}', '\u{00C1}',
    '\u{00CB}', '\u{00C8}', '\u{00CD}', '\u{00CE}', '\u{00CF}', '\u{00CC}', '\u{00D3}', '\u{00D4}',
    '\u{F8FF}', '\u{00D2}', '\u{00DA}', '\u{00DB}', '\u{00D9}', '\u{0131}', '\u{02C6}', '\u{02DC}',
    '\u{00AF}', '\u{02D8}', '\u{02D9}', '\u{02DA}', '\u{00B8}', '\u{02DD}', '\u{02DB}', '\u{02C7}',
];

/// The Mac OS Roman char code for a Unicode scalar (reverse of the table
/// above; ASCII is identity). PDFium `CharCodeFromUnicodeForEncoding`
/// (`kAppleRoman`) analog — the route into a font whose only cmap is the
/// Macintosh (1,0) subtable.
pub fn macroman_code_for_char(c: char) -> Option<u8> {
    match c {
        '\u{20}'..='\u{7E}' => Some(c as u8),
        _ => MACROMAN_HIGH
            .iter()
            .position(|&m| m == c)
            .map(|i| (i + 0x80) as u8),
    }
}

/// Resolve a PDF glyph name (from `/Differences`) to a Unicode scalar: the
/// algorithmic `uniXXXX`/`uXXXXXX` forms, then a compact standard-name table.
pub fn glyph_name_to_char(name: &[u8]) -> Option<char> {
    // uniXXXX (one BMP code point) — the common producer form.
    if let Some(hex) = name.strip_prefix(b"uni")
        && hex.len() == 4
        && let Ok(s) = std::str::from_utf8(hex)
        && let Ok(v) = u32::from_str_radix(s, 16)
    {
        return char::from_u32(v);
    }
    // uXXXX..XXXXXX
    if let Some(hex) = name.strip_prefix(b"u")
        && (4..=6).contains(&hex.len())
        && hex.iter().all(|b| b.is_ascii_hexdigit())
        && let Ok(s) = std::str::from_utf8(hex)
        && let Ok(v) = u32::from_str_radix(s, 16)
    {
        return char::from_u32(v);
    }
    if let Some(c) = standard_name_to_char(name) {
        return Some(c);
    }
    // The full Adobe Glyph List (4.3k names, binary search), then the AGL
    // rule for suffixed variants: `name.suffix` resolves as `name`.
    if let Some(c) = agl_lookup(name) {
        return Some(c);
    }
    let base = name.split(|&b| b == b'.').next().unwrap_or(name);
    if base.len() < name.len() {
        return glyph_name_to_char(base);
    }
    None
}

/// Binary search of the bundled full AGL (sorted by name).
fn agl_lookup(name: &[u8]) -> Option<char> {
    let table = crate::agl_table::AGL_NAMES;
    table
        .binary_search_by(|(n, _)| n.cmp(&name))
        .ok()
        .map(|i| table[i].1)
}

/// A compact Adobe Glyph List subset: the names used by StandardEncoding's
/// printable ASCII range (covers the vast majority of `/Differences` entries).
fn standard_name_to_char(name: &[u8]) -> Option<char> {
    let c = match name {
        b"space" => ' ',
        b"exclam" => '!',
        b"quotedbl" => '"',
        b"numbersign" => '#',
        b"dollar" => '$',
        b"percent" => '%',
        b"ampersand" => '&',
        b"quotesingle" => '\'',
        b"quoteright" => '\u{2019}',
        b"quoteleft" => '\u{2018}',
        b"parenleft" => '(',
        b"parenright" => ')',
        b"asterisk" => '*',
        b"plus" => '+',
        b"comma" => ',',
        b"hyphen" => '-',
        b"period" => '.',
        b"slash" => '/',
        b"zero" => '0',
        b"one" => '1',
        b"two" => '2',
        b"three" => '3',
        b"four" => '4',
        b"five" => '5',
        b"six" => '6',
        b"seven" => '7',
        b"eight" => '8',
        b"nine" => '9',
        b"colon" => ':',
        b"semicolon" => ';',
        b"less" => '<',
        b"equal" => '=',
        b"greater" => '>',
        b"question" => '?',
        b"at" => '@',
        b"bracketleft" => '[',
        b"backslash" => '\\',
        b"bracketright" => ']',
        b"asciicircum" => '^',
        b"underscore" => '_',
        b"grave" => '`',
        b"braceleft" => '{',
        b"bar" => '|',
        b"braceright" => '}',
        b"asciitilde" => '~',
        b"bullet" => '\u{2022}',
        b"endash" => '\u{2013}',
        b"emdash" => '\u{2014}',
        // Single-letter names (A..Z, a..z) are their own character.
        [b] if b.is_ascii_alphabetic() => *b as char,
        _ => return None,
    };
    Some(c)
}

/// Look a code up in a built-in encoding table; `0` marks an unused code.
fn table_char(table: &[u16; 256], code: u8) -> Option<char> {
    match table[code as usize] {
        0 => None,
        u => char::from_u32(u as u32),
    }
}

/// The built-in encoding of the standard Symbol face (ISO 32000-1 Annex D.5/D.6):
/// character code to Unicode scalar, `0` where the code is unused. Ported
/// from PDFium's `kAdobeSymbolEncoding` (`core/fpdfapi/font/cpdf_fontencoding.cpp`) — PDF
/// semantics, which fonts.md marks as the portable part of its font stack.
pub const SYMBOL_ENCODING: [u16; 256] = [
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0020, 0x0021, 0x2200, 0x0023,
    0x2203, 0x0025, 0x0026, 0x220B, 0x0028, 0x0029, 0x2217, 0x002B, 0x002C, 0x2212, 0x002E, 0x002F,
    0x0030, 0x0031, 0x0032, 0x0033, 0x0034, 0x0035, 0x0036, 0x0037, 0x0038, 0x0039, 0x003A, 0x003B,
    0x003C, 0x003D, 0x003E, 0x003F, 0x2245, 0x0391, 0x0392, 0x03A7, 0x0394, 0x0395, 0x03A6, 0x0393,
    0x0397, 0x0399, 0x03D1, 0x039A, 0x039B, 0x039C, 0x039D, 0x039F, 0x03A0, 0x0398, 0x03A1, 0x03A3,
    0x03A4, 0x03A5, 0x03C2, 0x03A9, 0x039E, 0x03A8, 0x0396, 0x005B, 0x2234, 0x005D, 0x22A5, 0x005F,
    0xF8E5, 0x03B1, 0x03B2, 0x03C7, 0x03B4, 0x03B5, 0x03C6, 0x03B3, 0x03B7, 0x03B9, 0x03D5, 0x03BA,
    0x03BB, 0x03BC, 0x03BD, 0x03BF, 0x03C0, 0x03B8, 0x03C1, 0x03C3, 0x03C4, 0x03C5, 0x03D6, 0x03C9,
    0x03BE, 0x03C8, 0x03B6, 0x007B, 0x007C, 0x007D, 0x223C, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x20AC, 0x03D2, 0x2032, 0x2264, 0x2044, 0x221E, 0x0192, 0x2663,
    0x2666, 0x2665, 0x2660, 0x2194, 0x2190, 0x2191, 0x2192, 0x2193, 0x00B0, 0x00B1, 0x2033, 0x2265,
    0x00D7, 0x221D, 0x2202, 0x2022, 0x00F7, 0x2260, 0x2261, 0x2248, 0x2026, 0xF8E6, 0xF8E7, 0x21B5,
    0x2135, 0x2111, 0x211C, 0x2118, 0x2297, 0x2295, 0x2205, 0x2229, 0x222A, 0x2283, 0x2287, 0x2284,
    0x2282, 0x2286, 0x2208, 0x2209, 0x2220, 0x2207, 0xF6DA, 0xF6D9, 0xF6DB, 0x220F, 0x221A, 0x22C5,
    0x00AC, 0x2227, 0x2228, 0x21D4, 0x21D0, 0x21D1, 0x21D2, 0x21D3, 0x25CA, 0x2329, 0xF8E8, 0xF8E9,
    0xF8EA, 0x2211, 0xF8EB, 0xF8EC, 0xF8ED, 0xF8EE, 0xF8EF, 0xF8F0, 0xF8F1, 0xF8F2, 0xF8F3, 0xF8F4,
    0x0000, 0x232A, 0x222B, 0x2320, 0xF8F5, 0x2321, 0xF8F6, 0xF8F7, 0xF8F8, 0xF8F9, 0xF8FA, 0xF8FB,
    0xF8FC, 0xF8FD, 0xF8FE, 0x0000,
];

/// The built-in encoding of the standard ZapfDingbats face (ISO 32000-1 Annex D.5/D.6):
/// character code to Unicode scalar, `0` where the code is unused. Ported
/// from PDFium's `kZapfEncoding` (`core/fpdfapi/font/cpdf_fontencoding.cpp`) — PDF
/// semantics, which fonts.md marks as the portable part of its font stack.
pub const ZAPF_ENCODING: [u16; 256] = [
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0020, 0x2701, 0x2702, 0x2703,
    0x2704, 0x260E, 0x2706, 0x2707, 0x2708, 0x2709, 0x261B, 0x261E, 0x270C, 0x270D, 0x270E, 0x270F,
    0x2710, 0x2711, 0x2712, 0x2713, 0x2714, 0x2715, 0x2716, 0x2717, 0x2718, 0x2719, 0x271A, 0x271B,
    0x271C, 0x271D, 0x271E, 0x271F, 0x2720, 0x2721, 0x2722, 0x2723, 0x2724, 0x2725, 0x2726, 0x2727,
    0x2605, 0x2729, 0x272A, 0x272B, 0x272C, 0x272D, 0x272E, 0x272F, 0x2730, 0x2731, 0x2732, 0x2733,
    0x2734, 0x2735, 0x2736, 0x2737, 0x2738, 0x2739, 0x273A, 0x273B, 0x273C, 0x273D, 0x273E, 0x273F,
    0x2740, 0x2741, 0x2742, 0x2743, 0x2744, 0x2745, 0x2746, 0x2747, 0x2748, 0x2749, 0x274A, 0x274B,
    0x25CF, 0x274D, 0x25A0, 0x274F, 0x2750, 0x2751, 0x2752, 0x25B2, 0x25BC, 0x25C6, 0x2756, 0x25D7,
    0x2758, 0x2759, 0x275A, 0x275B, 0x275C, 0x275D, 0x275E, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,
    0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x2761, 0x2762, 0x2763, 0x2764, 0x2765, 0x2766, 0x2767,
    0x2663, 0x2666, 0x2665, 0x2660, 0x2460, 0x2461, 0x2462, 0x2463, 0x2464, 0x2465, 0x2466, 0x2467,
    0x2468, 0x2469, 0x2776, 0x2777, 0x2778, 0x2779, 0x277A, 0x277B, 0x277C, 0x277D, 0x277E, 0x277F,
    0x2780, 0x2781, 0x2782, 0x2783, 0x2784, 0x2785, 0x2786, 0x2787, 0x2788, 0x2789, 0x278A, 0x278B,
    0x278C, 0x278D, 0x278E, 0x278F, 0x2790, 0x2791, 0x2792, 0x2793, 0x2794, 0x2192, 0x2194, 0x2195,
    0x2798, 0x2799, 0x279A, 0x279B, 0x279C, 0x279D, 0x279E, 0x279F, 0x27A0, 0x27A1, 0x27A2, 0x27A3,
    0x27A4, 0x27A5, 0x27A6, 0x27A7, 0x27A8, 0x27A9, 0x27AA, 0x27AB, 0x27AC, 0x27AD, 0x27AE, 0x27AF,
    0x0000, 0x27B1, 0x27B2, 0x27B3, 0x27B4, 0x27B5, 0x27B6, 0x27B7, 0x27B8, 0x27B9, 0x27BA, 0x27BB,
    0x27BC, 0x27BD, 0x27BE, 0x0000,
];

/// The glyph name an encoding assigns to `code`.
///
/// PDF simple-font encoding is defined code → **name** → glyph; Unicode is
/// not in the loop, and routing through it loses glyphs (AGL's `mu` is
/// U+00B5, not Symbol's U+03BC; Dingbats' `a1`..`a191` have no Unicode names
/// at all) and fails outright for a font whose only name table is `post` —
/// which is every bare CFF we wrap.
pub fn builtin_glyph_name(encoding: BaseEncoding, code: u8) -> Option<&'static [u8]> {
    let table: &[Option<&[u8]>; 224] = match encoding {
        BaseEncoding::SymbolFont => &SYMBOL_NAMES,
        BaseEncoding::ZapfDingbats => &ZAPF_NAMES,
        BaseEncoding::Standard => &STANDARD_NAMES,
        BaseEncoding::WinAnsi => &WINANSI_NAMES,
        BaseEncoding::MacRoman => &MACROMAN_NAMES,
        BaseEncoding::MacExpert => &MACEXPERT_NAMES,
        // A symbolic font with no named encoding is addressed by raw code
        // through its own cmap, not by name.
        BaseEncoding::Symbolic => return None,
    };
    let idx = (code as usize).checked_sub(32)?;
    table.get(idx).copied().flatten()
}

/// Glyph names of the standard Symbol face's built-in encoding, indexed from
/// character code 32 (ISO 32000-1 Annex D). Ported from PDFium's `kAdobeSymbolEncodingNames`.
///
/// Names, not Unicode: the Adobe Glyph List is ambiguous here (`mu` means
/// U+00B5, but Symbol's code 0x6D wants U+03BC) and the Dingbats glyphs
/// (`a1`..`a191`) have no Unicode names at all, so only the name reaches
/// the right glyph.
pub const SYMBOL_NAMES: [Option<&[u8]>; 224] = [
    Some(b"space"),
    Some(b"exclam"),
    Some(b"universal"),
    Some(b"numbersign"),
    Some(b"existential"),
    Some(b"percent"),
    Some(b"ampersand"),
    Some(b"suchthat"),
    Some(b"parenleft"),
    Some(b"parenright"),
    Some(b"asteriskmath"),
    Some(b"plus"),
    Some(b"comma"),
    Some(b"minus"),
    Some(b"period"),
    Some(b"slash"),
    Some(b"zero"),
    Some(b"one"),
    Some(b"two"),
    Some(b"three"),
    Some(b"four"),
    Some(b"five"),
    Some(b"six"),
    Some(b"seven"),
    Some(b"eight"),
    Some(b"nine"),
    Some(b"colon"),
    Some(b"semicolon"),
    Some(b"less"),
    Some(b"equal"),
    Some(b"greater"),
    Some(b"question"),
    Some(b"congruent"),
    Some(b"Alpha"),
    Some(b"Beta"),
    Some(b"Chi"),
    Some(b"Delta"),
    Some(b"Epsilon"),
    Some(b"Phi"),
    Some(b"Gamma"),
    Some(b"Eta"),
    Some(b"Iota"),
    Some(b"theta1"),
    Some(b"Kappa"),
    Some(b"Lambda"),
    Some(b"Mu"),
    Some(b"Nu"),
    Some(b"Omicron"),
    Some(b"Pi"),
    Some(b"Theta"),
    Some(b"Rho"),
    Some(b"Sigma"),
    Some(b"Tau"),
    Some(b"Upsilon"),
    Some(b"sigma1"),
    Some(b"Omega"),
    Some(b"Xi"),
    Some(b"Psi"),
    Some(b"Zeta"),
    Some(b"bracketleft"),
    Some(b"therefore"),
    Some(b"bracketright"),
    Some(b"perpendicular"),
    Some(b"underscore"),
    Some(b"radicalex"),
    Some(b"alpha"),
    Some(b"beta"),
    Some(b"chi"),
    Some(b"delta"),
    Some(b"epsilon"),
    Some(b"phi"),
    Some(b"gamma"),
    Some(b"eta"),
    Some(b"iota"),
    Some(b"phi1"),
    Some(b"kappa"),
    Some(b"lambda"),
    Some(b"mu"),
    Some(b"nu"),
    Some(b"omicron"),
    Some(b"pi"),
    Some(b"theta"),
    Some(b"rho"),
    Some(b"sigma"),
    Some(b"tau"),
    Some(b"upsilon"),
    Some(b"omega1"),
    Some(b"omega"),
    Some(b"xi"),
    Some(b"psi"),
    Some(b"zeta"),
    Some(b"braceleft"),
    Some(b"bar"),
    Some(b"braceright"),
    Some(b"similar"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some(b"Euro"),
    Some(b"Upsilon1"),
    Some(b"minute"),
    Some(b"lessequal"),
    Some(b"fraction"),
    Some(b"infinity"),
    Some(b"florin"),
    Some(b"club"),
    Some(b"diamond"),
    Some(b"heart"),
    Some(b"spade"),
    Some(b"arrowboth"),
    Some(b"arrowleft"),
    Some(b"arrowup"),
    Some(b"arrowright"),
    Some(b"arrowdown"),
    Some(b"degree"),
    Some(b"plusminus"),
    Some(b"second"),
    Some(b"greaterequal"),
    Some(b"multiply"),
    Some(b"proportional"),
    Some(b"partialdiff"),
    Some(b"bullet"),
    Some(b"divide"),
    Some(b"notequal"),
    Some(b"equivalence"),
    Some(b"approxequal"),
    Some(b"ellipsis"),
    Some(b"arrowvertex"),
    Some(b"arrowhorizex"),
    Some(b"carriagereturn"),
    Some(b"aleph"),
    Some(b"Ifraktur"),
    Some(b"Rfraktur"),
    Some(b"weierstrass"),
    Some(b"circlemultiply"),
    Some(b"circleplus"),
    Some(b"emptyset"),
    Some(b"intersection"),
    Some(b"union"),
    Some(b"propersuperset"),
    Some(b"reflexsuperset"),
    Some(b"notsubset"),
    Some(b"propersubset"),
    Some(b"reflexsubset"),
    Some(b"element"),
    Some(b"notelement"),
    Some(b"angle"),
    Some(b"gradient"),
    Some(b"registerserif"),
    Some(b"copyrightserif"),
    Some(b"trademarkserif"),
    Some(b"product"),
    Some(b"radical"),
    Some(b"dotmath"),
    Some(b"logicalnot"),
    Some(b"logicaland"),
    Some(b"logicalor"),
    Some(b"arrowdblboth"),
    Some(b"arrowdblleft"),
    Some(b"arrowdblup"),
    Some(b"arrowdblright"),
    Some(b"arrowdbldown"),
    Some(b"lozenge"),
    Some(b"angleleft"),
    Some(b"registersans"),
    Some(b"copyrightsans"),
    Some(b"trademarksans"),
    Some(b"summation"),
    Some(b"parenlefttp"),
    Some(b"parenleftex"),
    Some(b"parenleftbt"),
    Some(b"bracketlefttp"),
    Some(b"bracketleftex"),
    Some(b"bracketleftbt"),
    Some(b"bracelefttp"),
    Some(b"braceleftmid"),
    Some(b"braceleftbt"),
    Some(b"braceex"),
    None,
    Some(b"angleright"),
    Some(b"integral"),
    Some(b"integraltp"),
    Some(b"integralex"),
    Some(b"integralbt"),
    Some(b"parenrighttp"),
    Some(b"parenrightex"),
    Some(b"parenrightbt"),
    Some(b"bracketrighttp"),
    Some(b"bracketrightex"),
    Some(b"bracketrightbt"),
    Some(b"bracerighttp"),
    Some(b"bracerightmid"),
    Some(b"bracerightbt"),
    None,
];

/// Glyph names of the standard ZapfDingbats face's built-in encoding, indexed from
/// character code 32 (ISO 32000-1 Annex D). Ported from PDFium's `kZapfEncodingNames`.
///
/// Names, not Unicode: the Adobe Glyph List is ambiguous here (`mu` means
/// U+00B5, but Symbol's code 0x6D wants U+03BC) and the Dingbats glyphs
/// (`a1`..`a191`) have no Unicode names at all, so only the name reaches
/// the right glyph.
pub const ZAPF_NAMES: [Option<&[u8]>; 224] = [
    Some(b"space"),
    Some(b"a1"),
    Some(b"a2"),
    Some(b"a202"),
    Some(b"a3"),
    Some(b"a4"),
    Some(b"a5"),
    Some(b"a119"),
    Some(b"a118"),
    Some(b"a117"),
    Some(b"a11"),
    Some(b"a12"),
    Some(b"a13"),
    Some(b"a14"),
    Some(b"a15"),
    Some(b"a16"),
    Some(b"a105"),
    Some(b"a17"),
    Some(b"a18"),
    Some(b"a19"),
    Some(b"a20"),
    Some(b"a21"),
    Some(b"a22"),
    Some(b"a23"),
    Some(b"a24"),
    Some(b"a25"),
    Some(b"a26"),
    Some(b"a27"),
    Some(b"a28"),
    Some(b"a6"),
    Some(b"a7"),
    Some(b"a8"),
    Some(b"a9"),
    Some(b"a10"),
    Some(b"a29"),
    Some(b"a30"),
    Some(b"a31"),
    Some(b"a32"),
    Some(b"a33"),
    Some(b"a34"),
    Some(b"a35"),
    Some(b"a36"),
    Some(b"a37"),
    Some(b"a38"),
    Some(b"a39"),
    Some(b"a40"),
    Some(b"a41"),
    Some(b"a42"),
    Some(b"a43"),
    Some(b"a44"),
    Some(b"a45"),
    Some(b"a46"),
    Some(b"a47"),
    Some(b"a48"),
    Some(b"a49"),
    Some(b"a50"),
    Some(b"a51"),
    Some(b"a52"),
    Some(b"a53"),
    Some(b"a54"),
    Some(b"a55"),
    Some(b"a56"),
    Some(b"a57"),
    Some(b"a58"),
    Some(b"a59"),
    Some(b"a60"),
    Some(b"a61"),
    Some(b"a62"),
    Some(b"a63"),
    Some(b"a64"),
    Some(b"a65"),
    Some(b"a66"),
    Some(b"a67"),
    Some(b"a68"),
    Some(b"a69"),
    Some(b"a70"),
    Some(b"a71"),
    Some(b"a72"),
    Some(b"a73"),
    Some(b"a74"),
    Some(b"a203"),
    Some(b"a75"),
    Some(b"a204"),
    Some(b"a76"),
    Some(b"a77"),
    Some(b"a78"),
    Some(b"a79"),
    Some(b"a81"),
    Some(b"a82"),
    Some(b"a83"),
    Some(b"a84"),
    Some(b"a97"),
    Some(b"a98"),
    Some(b"a99"),
    Some(b"a100"),
    None,
    Some(b"a89"),
    Some(b"a90"),
    Some(b"a93"),
    Some(b"a94"),
    Some(b"a91"),
    Some(b"a92"),
    Some(b"a205"),
    Some(b"a85"),
    Some(b"a206"),
    Some(b"a86"),
    Some(b"a87"),
    Some(b"a88"),
    Some(b"a95"),
    Some(b"a96"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some(b"a101"),
    Some(b"a102"),
    Some(b"a103"),
    Some(b"a104"),
    Some(b"a106"),
    Some(b"a107"),
    Some(b"a108"),
    Some(b"a112"),
    Some(b"a111"),
    Some(b"a110"),
    Some(b"a109"),
    Some(b"a120"),
    Some(b"a121"),
    Some(b"a122"),
    Some(b"a123"),
    Some(b"a124"),
    Some(b"a125"),
    Some(b"a126"),
    Some(b"a127"),
    Some(b"a128"),
    Some(b"a129"),
    Some(b"a130"),
    Some(b"a131"),
    Some(b"a132"),
    Some(b"a133"),
    Some(b"a134"),
    Some(b"a135"),
    Some(b"a136"),
    Some(b"a137"),
    Some(b"a138"),
    Some(b"a139"),
    Some(b"a140"),
    Some(b"a141"),
    Some(b"a142"),
    Some(b"a143"),
    Some(b"a144"),
    Some(b"a145"),
    Some(b"a146"),
    Some(b"a147"),
    Some(b"a148"),
    Some(b"a149"),
    Some(b"a150"),
    Some(b"a151"),
    Some(b"a152"),
    Some(b"a153"),
    Some(b"a154"),
    Some(b"a155"),
    Some(b"a156"),
    Some(b"a157"),
    Some(b"a158"),
    Some(b"a159"),
    Some(b"a160"),
    Some(b"a161"),
    Some(b"a163"),
    Some(b"a164"),
    Some(b"a196"),
    Some(b"a165"),
    Some(b"a192"),
    Some(b"a166"),
    Some(b"a167"),
    Some(b"a168"),
    Some(b"a169"),
    Some(b"a170"),
    Some(b"a171"),
    Some(b"a172"),
    Some(b"a173"),
    Some(b"a162"),
    Some(b"a174"),
    Some(b"a175"),
    Some(b"a176"),
    Some(b"a177"),
    Some(b"a178"),
    Some(b"a179"),
    Some(b"a193"),
    Some(b"a180"),
    Some(b"a199"),
    Some(b"a181"),
    Some(b"a200"),
    Some(b"a182"),
    None,
    Some(b"a201"),
    Some(b"a183"),
    Some(b"a184"),
    Some(b"a197"),
    Some(b"a185"),
    Some(b"a194"),
    Some(b"a198"),
    Some(b"a186"),
    Some(b"a195"),
    Some(b"a187"),
    Some(b"a188"),
    Some(b"a189"),
    Some(b"a190"),
    Some(b"a191"),
    None,
];

/// Glyph names of StandardEncoding (Annex D.2), indexed from character code 32.
/// Ported from PDFium's `kStandardEncodingNames`.
pub const STANDARD_NAMES: [Option<&[u8]>; 224] = [
    Some(b"space"),
    Some(b"exclam"),
    Some(b"quotedbl"),
    Some(b"numbersign"),
    Some(b"dollar"),
    Some(b"percent"),
    Some(b"ampersand"),
    Some(b"quoteright"),
    Some(b"parenleft"),
    Some(b"parenright"),
    Some(b"asterisk"),
    Some(b"plus"),
    Some(b"comma"),
    Some(b"hyphen"),
    Some(b"period"),
    Some(b"slash"),
    Some(b"zero"),
    Some(b"one"),
    Some(b"two"),
    Some(b"three"),
    Some(b"four"),
    Some(b"five"),
    Some(b"six"),
    Some(b"seven"),
    Some(b"eight"),
    Some(b"nine"),
    Some(b"colon"),
    Some(b"semicolon"),
    Some(b"less"),
    Some(b"equal"),
    Some(b"greater"),
    Some(b"question"),
    Some(b"at"),
    Some(b"A"),
    Some(b"B"),
    Some(b"C"),
    Some(b"D"),
    Some(b"E"),
    Some(b"F"),
    Some(b"G"),
    Some(b"H"),
    Some(b"I"),
    Some(b"J"),
    Some(b"K"),
    Some(b"L"),
    Some(b"M"),
    Some(b"N"),
    Some(b"O"),
    Some(b"P"),
    Some(b"Q"),
    Some(b"R"),
    Some(b"S"),
    Some(b"T"),
    Some(b"U"),
    Some(b"V"),
    Some(b"W"),
    Some(b"X"),
    Some(b"Y"),
    Some(b"Z"),
    Some(b"bracketleft"),
    Some(b"backslash"),
    Some(b"bracketright"),
    Some(b"asciicircum"),
    Some(b"underscore"),
    Some(b"quoteleft"),
    Some(b"a"),
    Some(b"b"),
    Some(b"c"),
    Some(b"d"),
    Some(b"e"),
    Some(b"f"),
    Some(b"g"),
    Some(b"h"),
    Some(b"i"),
    Some(b"j"),
    Some(b"k"),
    Some(b"l"),
    Some(b"m"),
    Some(b"n"),
    Some(b"o"),
    Some(b"p"),
    Some(b"q"),
    Some(b"r"),
    Some(b"s"),
    Some(b"t"),
    Some(b"u"),
    Some(b"v"),
    Some(b"w"),
    Some(b"x"),
    Some(b"y"),
    Some(b"z"),
    Some(b"braceleft"),
    Some(b"bar"),
    Some(b"braceright"),
    Some(b"asciitilde"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some(b"exclamdown"),
    Some(b"cent"),
    Some(b"sterling"),
    Some(b"fraction"),
    Some(b"yen"),
    Some(b"florin"),
    Some(b"section"),
    Some(b"currency"),
    Some(b"quotesingle"),
    Some(b"quotedblleft"),
    Some(b"guillemotleft"),
    Some(b"guilsinglleft"),
    Some(b"guilsinglright"),
    Some(b"fi"),
    Some(b"fl"),
    None,
    Some(b"endash"),
    Some(b"dagger"),
    Some(b"daggerdbl"),
    Some(b"periodcentered"),
    None,
    Some(b"paragraph"),
    Some(b"bullet"),
    Some(b"quotesinglbase"),
    Some(b"quotedblbase"),
    Some(b"quotedblright"),
    Some(b"guillemotright"),
    Some(b"ellipsis"),
    Some(b"perthousand"),
    None,
    Some(b"questiondown"),
    None,
    Some(b"grave"),
    Some(b"acute"),
    Some(b"circumflex"),
    Some(b"tilde"),
    Some(b"macron"),
    Some(b"breve"),
    Some(b"dotaccent"),
    Some(b"dieresis"),
    None,
    Some(b"ring"),
    Some(b"cedilla"),
    None,
    Some(b"hungarumlaut"),
    Some(b"ogonek"),
    Some(b"caron"),
    Some(b"emdash"),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some(b"AE"),
    None,
    Some(b"ordfeminine"),
    None,
    None,
    None,
    None,
    Some(b"Lslash"),
    Some(b"Oslash"),
    Some(b"OE"),
    Some(b"ordmasculine"),
    None,
    None,
    None,
    None,
    None,
    Some(b"ae"),
    None,
    None,
    None,
    Some(b"dotlessi"),
    None,
    None,
    Some(b"lslash"),
    Some(b"oslash"),
    Some(b"oe"),
    Some(b"germandbls"),
    None,
    None,
    None,
    None,
];

/// Glyph names of WinAnsiEncoding (Annex D.2), indexed from character code 32.
/// Ported from PDFium's `kAdobeWinAnsiEncodingNames`.
pub const WINANSI_NAMES: [Option<&[u8]>; 224] = [
    Some(b"space"),
    Some(b"exclam"),
    Some(b"quotedbl"),
    Some(b"numbersign"),
    Some(b"dollar"),
    Some(b"percent"),
    Some(b"ampersand"),
    Some(b"quotesingle"),
    Some(b"parenleft"),
    Some(b"parenright"),
    Some(b"asterisk"),
    Some(b"plus"),
    Some(b"comma"),
    Some(b"hyphen"),
    Some(b"period"),
    Some(b"slash"),
    Some(b"zero"),
    Some(b"one"),
    Some(b"two"),
    Some(b"three"),
    Some(b"four"),
    Some(b"five"),
    Some(b"six"),
    Some(b"seven"),
    Some(b"eight"),
    Some(b"nine"),
    Some(b"colon"),
    Some(b"semicolon"),
    Some(b"less"),
    Some(b"equal"),
    Some(b"greater"),
    Some(b"question"),
    Some(b"at"),
    Some(b"A"),
    Some(b"B"),
    Some(b"C"),
    Some(b"D"),
    Some(b"E"),
    Some(b"F"),
    Some(b"G"),
    Some(b"H"),
    Some(b"I"),
    Some(b"J"),
    Some(b"K"),
    Some(b"L"),
    Some(b"M"),
    Some(b"N"),
    Some(b"O"),
    Some(b"P"),
    Some(b"Q"),
    Some(b"R"),
    Some(b"S"),
    Some(b"T"),
    Some(b"U"),
    Some(b"V"),
    Some(b"W"),
    Some(b"X"),
    Some(b"Y"),
    Some(b"Z"),
    Some(b"bracketleft"),
    Some(b"backslash"),
    Some(b"bracketright"),
    Some(b"asciicircum"),
    Some(b"underscore"),
    Some(b"grave"),
    Some(b"a"),
    Some(b"b"),
    Some(b"c"),
    Some(b"d"),
    Some(b"e"),
    Some(b"f"),
    Some(b"g"),
    Some(b"h"),
    Some(b"i"),
    Some(b"j"),
    Some(b"k"),
    Some(b"l"),
    Some(b"m"),
    Some(b"n"),
    Some(b"o"),
    Some(b"p"),
    Some(b"q"),
    Some(b"r"),
    Some(b"s"),
    Some(b"t"),
    Some(b"u"),
    Some(b"v"),
    Some(b"w"),
    Some(b"x"),
    Some(b"y"),
    Some(b"z"),
    Some(b"braceleft"),
    Some(b"bar"),
    Some(b"braceright"),
    Some(b"asciitilde"),
    Some(b"bullet"),
    Some(b"Euro"),
    Some(b"bullet"),
    Some(b"quotesinglbase"),
    Some(b"florin"),
    Some(b"quotedblbase"),
    Some(b"ellipsis"),
    Some(b"dagger"),
    Some(b"daggerdbl"),
    Some(b"circumflex"),
    Some(b"perthousand"),
    Some(b"Scaron"),
    Some(b"guilsinglleft"),
    Some(b"OE"),
    Some(b"bullet"),
    Some(b"Zcaron"),
    Some(b"bullet"),
    Some(b"bullet"),
    Some(b"quoteleft"),
    Some(b"quoteright"),
    Some(b"quotedblleft"),
    Some(b"quotedblright"),
    Some(b"bullet"),
    Some(b"endash"),
    Some(b"emdash"),
    Some(b"tilde"),
    Some(b"trademark"),
    Some(b"scaron"),
    Some(b"guilsinglright"),
    Some(b"oe"),
    Some(b"bullet"),
    Some(b"zcaron"),
    Some(b"Ydieresis"),
    Some(b"space"),
    Some(b"exclamdown"),
    Some(b"cent"),
    Some(b"sterling"),
    Some(b"currency"),
    Some(b"yen"),
    Some(b"brokenbar"),
    Some(b"section"),
    Some(b"dieresis"),
    Some(b"copyright"),
    Some(b"ordfeminine"),
    Some(b"guillemotleft"),
    Some(b"logicalnot"),
    Some(b"hyphen"),
    Some(b"registered"),
    Some(b"macron"),
    Some(b"degree"),
    Some(b"plusminus"),
    Some(b"twosuperior"),
    Some(b"threesuperior"),
    Some(b"acute"),
    Some(b"mu"),
    Some(b"paragraph"),
    Some(b"periodcentered"),
    Some(b"cedilla"),
    Some(b"onesuperior"),
    Some(b"ordmasculine"),
    Some(b"guillemotright"),
    Some(b"onequarter"),
    Some(b"onehalf"),
    Some(b"threequarters"),
    Some(b"questiondown"),
    Some(b"Agrave"),
    Some(b"Aacute"),
    Some(b"Acircumflex"),
    Some(b"Atilde"),
    Some(b"Adieresis"),
    Some(b"Aring"),
    Some(b"AE"),
    Some(b"Ccedilla"),
    Some(b"Egrave"),
    Some(b"Eacute"),
    Some(b"Ecircumflex"),
    Some(b"Edieresis"),
    Some(b"Igrave"),
    Some(b"Iacute"),
    Some(b"Icircumflex"),
    Some(b"Idieresis"),
    Some(b"Eth"),
    Some(b"Ntilde"),
    Some(b"Ograve"),
    Some(b"Oacute"),
    Some(b"Ocircumflex"),
    Some(b"Otilde"),
    Some(b"Odieresis"),
    Some(b"multiply"),
    Some(b"Oslash"),
    Some(b"Ugrave"),
    Some(b"Uacute"),
    Some(b"Ucircumflex"),
    Some(b"Udieresis"),
    Some(b"Yacute"),
    Some(b"Thorn"),
    Some(b"germandbls"),
    Some(b"agrave"),
    Some(b"aacute"),
    Some(b"acircumflex"),
    Some(b"atilde"),
    Some(b"adieresis"),
    Some(b"aring"),
    Some(b"ae"),
    Some(b"ccedilla"),
    Some(b"egrave"),
    Some(b"eacute"),
    Some(b"ecircumflex"),
    Some(b"edieresis"),
    Some(b"igrave"),
    Some(b"iacute"),
    Some(b"icircumflex"),
    Some(b"idieresis"),
    Some(b"eth"),
    Some(b"ntilde"),
    Some(b"ograve"),
    Some(b"oacute"),
    Some(b"ocircumflex"),
    Some(b"otilde"),
    Some(b"odieresis"),
    Some(b"divide"),
    Some(b"oslash"),
    Some(b"ugrave"),
    Some(b"uacute"),
    Some(b"ucircumflex"),
    Some(b"udieresis"),
    Some(b"yacute"),
    Some(b"thorn"),
    Some(b"ydieresis"),
];

/// Glyph names of MacRomanEncoding (Annex D.2), indexed from character code 32.
/// Ported from PDFium's `kMacRomanEncodingNames`.
pub const MACROMAN_NAMES: [Option<&[u8]>; 224] = [
    Some(b"space"),
    Some(b"exclam"),
    Some(b"quotedbl"),
    Some(b"numbersign"),
    Some(b"dollar"),
    Some(b"percent"),
    Some(b"ampersand"),
    Some(b"quotesingle"),
    Some(b"parenleft"),
    Some(b"parenright"),
    Some(b"asterisk"),
    Some(b"plus"),
    Some(b"comma"),
    Some(b"hyphen"),
    Some(b"period"),
    Some(b"slash"),
    Some(b"zero"),
    Some(b"one"),
    Some(b"two"),
    Some(b"three"),
    Some(b"four"),
    Some(b"five"),
    Some(b"six"),
    Some(b"seven"),
    Some(b"eight"),
    Some(b"nine"),
    Some(b"colon"),
    Some(b"semicolon"),
    Some(b"less"),
    Some(b"equal"),
    Some(b"greater"),
    Some(b"question"),
    Some(b"at"),
    Some(b"A"),
    Some(b"B"),
    Some(b"C"),
    Some(b"D"),
    Some(b"E"),
    Some(b"F"),
    Some(b"G"),
    Some(b"H"),
    Some(b"I"),
    Some(b"J"),
    Some(b"K"),
    Some(b"L"),
    Some(b"M"),
    Some(b"N"),
    Some(b"O"),
    Some(b"P"),
    Some(b"Q"),
    Some(b"R"),
    Some(b"S"),
    Some(b"T"),
    Some(b"U"),
    Some(b"V"),
    Some(b"W"),
    Some(b"X"),
    Some(b"Y"),
    Some(b"Z"),
    Some(b"bracketleft"),
    Some(b"backslash"),
    Some(b"bracketright"),
    Some(b"asciicircum"),
    Some(b"underscore"),
    Some(b"grave"),
    Some(b"a"),
    Some(b"b"),
    Some(b"c"),
    Some(b"d"),
    Some(b"e"),
    Some(b"f"),
    Some(b"g"),
    Some(b"h"),
    Some(b"i"),
    Some(b"j"),
    Some(b"k"),
    Some(b"l"),
    Some(b"m"),
    Some(b"n"),
    Some(b"o"),
    Some(b"p"),
    Some(b"q"),
    Some(b"r"),
    Some(b"s"),
    Some(b"t"),
    Some(b"u"),
    Some(b"v"),
    Some(b"w"),
    Some(b"x"),
    Some(b"y"),
    Some(b"z"),
    Some(b"braceleft"),
    Some(b"bar"),
    Some(b"braceright"),
    Some(b"asciitilde"),
    None,
    Some(b"Adieresis"),
    Some(b"Aring"),
    Some(b"Ccedilla"),
    Some(b"Eacute"),
    Some(b"Ntilde"),
    Some(b"Odieresis"),
    Some(b"Udieresis"),
    Some(b"aacute"),
    Some(b"agrave"),
    Some(b"acircumflex"),
    Some(b"adieresis"),
    Some(b"atilde"),
    Some(b"aring"),
    Some(b"ccedilla"),
    Some(b"eacute"),
    Some(b"egrave"),
    Some(b"ecircumflex"),
    Some(b"edieresis"),
    Some(b"iacute"),
    Some(b"igrave"),
    Some(b"icircumflex"),
    Some(b"idieresis"),
    Some(b"ntilde"),
    Some(b"oacute"),
    Some(b"ograve"),
    Some(b"ocircumflex"),
    Some(b"odieresis"),
    Some(b"otilde"),
    Some(b"uacute"),
    Some(b"ugrave"),
    Some(b"ucircumflex"),
    Some(b"udieresis"),
    Some(b"dagger"),
    Some(b"degree"),
    Some(b"cent"),
    Some(b"sterling"),
    Some(b"section"),
    Some(b"bullet"),
    Some(b"paragraph"),
    Some(b"germandbls"),
    Some(b"registered"),
    Some(b"copyright"),
    Some(b"trademark"),
    Some(b"acute"),
    Some(b"dieresis"),
    Some(b"notequal"),
    Some(b"AE"),
    Some(b"Oslash"),
    Some(b"infinity"),
    Some(b"plusminus"),
    Some(b"lessequal"),
    Some(b"greaterequal"),
    Some(b"yen"),
    Some(b"mu"),
    Some(b"partialdiff"),
    Some(b"summation"),
    Some(b"product"),
    Some(b"pi"),
    Some(b"integral"),
    Some(b"ordfeminine"),
    Some(b"ordmasculine"),
    Some(b"Omega"),
    Some(b"ae"),
    Some(b"oslash"),
    Some(b"questiondown"),
    Some(b"exclamdown"),
    Some(b"logicalnot"),
    Some(b"radical"),
    Some(b"florin"),
    Some(b"approxequal"),
    Some(b"Delta"),
    Some(b"guillemotleft"),
    Some(b"guillemotright"),
    Some(b"ellipsis"),
    Some(b"space"),
    Some(b"Agrave"),
    Some(b"Atilde"),
    Some(b"Otilde"),
    Some(b"OE"),
    Some(b"oe"),
    Some(b"endash"),
    Some(b"emdash"),
    Some(b"quotedblleft"),
    Some(b"quotedblright"),
    Some(b"quoteleft"),
    Some(b"quoteright"),
    Some(b"divide"),
    Some(b"lozenge"),
    Some(b"ydieresis"),
    Some(b"Ydieresis"),
    Some(b"fraction"),
    Some(b"currency"),
    Some(b"guilsinglleft"),
    Some(b"guilsinglright"),
    Some(b"fi"),
    Some(b"fl"),
    Some(b"daggerdbl"),
    Some(b"periodcentered"),
    Some(b"quotesinglbase"),
    Some(b"quotedblbase"),
    Some(b"perthousand"),
    Some(b"Acircumflex"),
    Some(b"Ecircumflex"),
    Some(b"Aacute"),
    Some(b"Edieresis"),
    Some(b"Egrave"),
    Some(b"Iacute"),
    Some(b"Icircumflex"),
    Some(b"Idieresis"),
    Some(b"Igrave"),
    Some(b"Oacute"),
    Some(b"Ocircumflex"),
    Some(b"apple"),
    Some(b"Ograve"),
    Some(b"Uacute"),
    Some(b"Ucircumflex"),
    Some(b"Ugrave"),
    Some(b"dotlessi"),
    Some(b"circumflex"),
    Some(b"tilde"),
    Some(b"macron"),
    Some(b"breve"),
    Some(b"dotaccent"),
    Some(b"ring"),
    Some(b"cedilla"),
    Some(b"hungarumlaut"),
    Some(b"ogonek"),
    Some(b"caron"),
];

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
    use super::*;

    #[test]
    fn full_agl_resolves_tail_names_and_dot_variants() {
        // Names beyond the compact subset resolve via the bundled AGL.
        assert_eq!(glyph_name_to_char(b"aleph"), Some('\u{2135}'));
        assert_eq!(glyph_name_to_char(b"Ohorn"), Some('\u{01A0}'));
        assert_eq!(glyph_name_to_char(b"afii10017"), Some('\u{0410}')); // Cyrillic A
        assert_eq!(glyph_name_to_char(b"longs"), Some('\u{017F}'));
        // AGL suffix rule: `name.suffix` resolves as `name`.
        assert_eq!(glyph_name_to_char(b"aleph.alt1"), Some('\u{2135}'));
        // Unknown names still miss.
        assert_eq!(glyph_name_to_char(b"notarealglyphname"), None);
    }

    #[test]
    fn macexpert_resolves_by_name_only() {
        assert_eq!(
            BaseEncoding::from_name(b"MacExpertEncoding"),
            Some(BaseEncoding::MacExpert)
        );
        // Annex D.4 spot checks (PDFium kMacExpertEncodingNames).
        assert_eq!(
            builtin_glyph_name(BaseEncoding::MacExpert, 0x20),
            Some(&b"space"[..])
        );
        assert_eq!(
            builtin_glyph_name(BaseEncoding::MacExpert, 0x21),
            Some(&b"exclamsmall"[..])
        );
        assert_eq!(
            builtin_glyph_name(BaseEncoding::MacExpert, 0x30),
            Some(&b"zerooldstyle"[..])
        );
        // Expert glyphs have names, not Unicode identities.
        assert_eq!(BaseEncoding::MacExpert.to_char(0x21), None);
        // A gap stays empty.
        assert_eq!(builtin_glyph_name(BaseEncoding::MacExpert, 0x80), None);
    }

    #[test]
    fn winansi_ascii_and_high() {
        assert_eq!(BaseEncoding::WinAnsi.to_char(b'A'), Some('A'));
        assert_eq!(BaseEncoding::WinAnsi.to_char(0x80), Some('\u{20AC}')); // euro
        assert_eq!(BaseEncoding::WinAnsi.to_char(0xE9), Some('é'));
        assert_eq!(BaseEncoding::WinAnsi.to_char(0x81), None); // undefined
    }

    #[test]
    fn differences_names() {
        assert_eq!(glyph_name_to_char(b"A"), Some('A'));
        assert_eq!(glyph_name_to_char(b"space"), Some(' '));
        assert_eq!(glyph_name_to_char(b"uni00E9"), Some('é'));
        assert_eq!(glyph_name_to_char(b"period"), Some('.'));
        assert_eq!(glyph_name_to_char(b"notaglyph"), None);
    }
}
