// src/iw44/constants.rs

// DjVu Spec Table 4: Initial step sizes for IW44 coefficients
// These are the exact values from the DjVu specification and IW44Image.cpp
pub const IW_QUANT: [i32; 16] = [
    0x004000,
    0x008000, 0x008000, 0x010000,
    0x010000, 0x010000, 0x020000,
    0x020000, 0x020000, 0x040000,
    0x040000, 0x040000, 0x080000,
    0x040000, 0x040000, 0x080000,
];

pub const IW_SHIFT: i32 = 6;
pub const IW_ROUND: i32 = 1 << (IW_SHIFT - 1); // = 32

// From IW44EncodeCodec.cpp - DECIBEL_PRUNE constant
pub const DECIBEL_PRUNE: f32 = 5.0;

// From IW44EncodeCodec.cpp - iw_norm array for wavelet norms
pub const IW_NORM: [f32; 16] = [
    2.627989e+03,
    1.832893e+02, 1.832959e+02, 5.114690e+01,
    4.583344e+01, 4.583462e+01, 1.279225e+01,
    1.149671e+01, 1.149712e+01, 3.218888e+00,
    2.999281e+00, 2.999476e+00, 8.733161e-01,
    1.074451e+00, 1.074511e+00, 4.289318e-01,
];

#[derive(Debug, Copy, Clone)]
pub struct BandBucketInfo {
    pub start: usize,
    pub size: usize,
}

pub const BAND_BUCKETS: [BandBucketInfo; 10] = [
    BandBucketInfo { start: 0, size: 1 },   // Band 0: bucket 0      (coeffs 0-15, DC band)
    BandBucketInfo { start: 1, size: 1 },   // Band 1: bucket 1      (coeffs 16-31)
    BandBucketInfo { start: 2, size: 1 },   // Band 2: bucket 2      (coeffs 32-47)
    BandBucketInfo { start: 3, size: 1 },   // Band 3: bucket 3      (coeffs 48-63)
    BandBucketInfo { start: 4, size: 4 },   // Band 4: buckets 4-7   (coeffs 64-127)
    BandBucketInfo { start: 8, size: 4 },   // Band 5: buckets 8-11  (coeffs 128-191)
    BandBucketInfo { start: 12, size: 4 },  // Band 6: buckets 12-15 (coeffs 192-255)
    BandBucketInfo { start: 16, size: 16 }, // Band 7: buckets 16-31 (coeffs 256-511)
    BandBucketInfo { start: 32, size: 16 }, // Band 8: buckets 32-47 (coeffs 512-767)
    BandBucketInfo { start: 48, size: 16 }, // Band 9: buckets 48-63 (coeffs 768-1023)
];

// Generated from the C++ `zigzagloc` array.
// In a real project, this would be generated by a build script.
#[rustfmt::skip]
pub const ZIGZAG_LOC: [usize; 1024] = include!("zigzag_loc.txt");
