[package]
name = "freya-render-tiny-skia"
version = "0.4.0-rc.17"
description = "Tiny-skia CPU renderer for Freya"
edition = "2024"
license = "MIT"
authors = ["Marc Espín <mespinsanz@gmail.com>"]
readme = "../../README.md"
homepage = "https://freyaui.dev/"
repository = "https://github.com/marc2332/freya"

[lints]
workspace = true

[dependencies]
freya-render-api = { workspace = true }
tiny-skia = { workspace = true }
