/*
 * lege_render.h -- C ABI for the Lege PDF renderer.
 *
 * GENERATED by cbindgen from src/lib.rs. Do not edit by hand.
 *
 * LICENSING: this library links the Lege renderer, which is AGPL-3.0-only.
 * Anything you distribute against it is a combined AGPL work, including when
 * users reach it over a network (AGPL section 13).
 */

#ifndef LEGE_RENDER_H
#define LEGE_RENDER_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Call succeeded.
 */
#define LEGE_OK 0

/**
 * A required pointer argument was null.
 */
#define LEGE_ERR_NULL_ARGUMENT -1

/**
 * An argument was outside its valid range (a bad page index, a bad DPI).
 */
#define LEGE_ERR_INVALID_ARGUMENT -2

/**
 * The document could not be opened or decrypted.
 */
#define LEGE_ERR_OPEN -3

/**
 * The page could not be parsed or rendered.
 */
#define LEGE_ERR_RENDER -4

/**
 * The image could not be encoded.
 */
#define LEGE_ERR_ENCODE -5

/**
 * The requested raster exceeds the pixel budget.
 */
#define LEGE_ERR_TOO_LARGE -6

/**
 * The renderer panicked. The library remains usable; the document may not be.
 */
#define LEGE_ERR_PANIC -7

/**
 * Output container for [`lege_document_render_page`].
 */
#define LEGE_FORMAT_PNG 0

/**
 * Baseline JPEG.
 */
#define LEGE_FORMAT_JPEG 1

/**
 * 8-bit RGB output.
 */
#define LEGE_COLOR_RGB 0

/**
 * 8-bit grayscale output.
 */
#define LEGE_COLOR_GRAY 1

/**
 * A cancellation token. Opaque, shareable across threads, and the reason a
 * slow render does not have to be waited out.
 */
typedef struct LegeCancellation LegeCancellation;

/**
 * An opened PDF document. Opaque: its layout is not part of the ABI.
 */
typedef struct LegeDocument LegeDocument;

/**
 * An owned byte buffer produced by this library.
 *
 * Free it with [`lege_buffer_free`] and nothing else: it was allocated by
 * Rust, and passing it to C `free()` is undefined behaviour. `capacity` is
 * carried because Rust's deallocator needs the original allocation size.
 */
typedef struct LegeBuffer {
  uint8_t *data;
  size_t len;
  size_t capacity;
} LegeBuffer;

/**
 * How to render one page.
 *
 * `#[repr(C)]` and deliberately frozen: adding a field here is an ABI break
 * for every already-compiled caller. New knobs get a new function.
 */
typedef struct LegeRenderOptions {
  /**
   * Target resolution in dots per inch.
   */
  double dpi;
  /**
   * One of `LEGE_FORMAT_*`.
   */
  int format;
  /**
   * One of `LEGE_COLOR_*`.
   */
  int color;
  /**
   * JPEG quality, 1-100. Ignored for PNG.
   */
  int jpeg_quality;
  /**
   * Reject renders whose pixel count exceeds this. 0 means the library
   * default (about 100 megapixels).
   */
  uint64_t max_pixels;
} LegeRenderOptions;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Message for the most recent failure **on the calling thread**, or `NULL`
 * if the last call succeeded.
 *
 * The pointer is owned by the library and stays valid until the next failing
 * call on this thread. Copy it if you need to keep it; do not free it.
 *
 * # Safety
 * The returned pointer must not be used after another library call on this
 * thread.
 */
const char *lege_last_error_message(void);

/**
 * Release a buffer produced by this library. Safe to call on a zeroed or
 * already-emptied buffer; the fields are cleared so a double free is a no-op.
 *
 * # Safety
 * `buffer` must be null, or point to a [`LegeBuffer`] this library filled in
 * and that has not already been freed.
 */
void lege_buffer_free(struct LegeBuffer *buffer);

/**
 * Open a PDF from memory.
 *
 * The bytes are copied, so the caller may free `data` immediately. Pass
 * `password` as `NULL` for an unencrypted document, or an empty string for
 * one encrypted with the empty user password.
 *
 * Returns `NULL` on failure; call [`lege_last_error_message`] for why.
 *
 * # Safety
 * `data` must point to at least `len` readable bytes, and `password`, when
 * non-null, must be a NUL-terminated C string.
 */
struct LegeDocument *lege_document_open(const uint8_t *data, size_t len, const char *password);

/**
 * Close a document opened by [`lege_document_open`]. Null is ignored.
 *
 * # Safety
 * `document` must be null or a handle from [`lege_document_open`] that has
 * not already been closed, and no other thread may be using it.
 */
void lege_document_close(struct LegeDocument *document);

/**
 * Number of pages, or 0 if `document` is null.
 *
 * # Safety
 * `document` must be null or a valid open handle.
 */
unsigned int lege_document_page_count(const struct LegeDocument *document);

/**
 * Visible size of a page in PDF points (1/72 inch), with `/Rotate` applied so
 * the values match what a viewer displays.
 *
 * # Safety
 * `document` must be a valid open handle; `width` and `height` must point to
 * writable `double`s.
 */
int lege_document_page_size(const struct LegeDocument *document,
                            unsigned int page,
                            double *width,
                            double *height);

/**
 * Pixel size a page would render to at `dpi`, without rendering it.
 *
 * # Safety
 * As [`lege_document_page_size`], with `uint32_t` out-parameters.
 */
int lege_document_page_pixel_size(const struct LegeDocument *document,
                                  unsigned int page,
                                  double dpi,
                                  unsigned int *width,
                                  unsigned int *height);

/**
 * Create a cancellation token. Returns `NULL` only on allocation failure.
 */
struct LegeCancellation *lege_cancellation_new(void);

/**
 * Signal cancellation. Safe to call from any thread, including while a render
 * using this token is in flight -- that is the point of it.
 *
 * # Safety
 * `token` must be null or a live handle from [`lege_cancellation_new`].
 */
void lege_cancellation_cancel(const struct LegeCancellation *token);

/**
 * Whether this token has been cancelled.
 *
 * # Safety
 * `token` must be null or a live handle from [`lege_cancellation_new`].
 */
int lege_cancellation_is_cancelled(const struct LegeCancellation *token);

/**
 * Free a cancellation token. Null is ignored.
 *
 * # Safety
 * `token` must be null or a handle that has not already been freed, and no
 * render using it may still be running.
 */
void lege_cancellation_free(struct LegeCancellation *token);

/**
 * Options equivalent to a 150 DPI RGB PNG at the default pixel budget.
 *
 * Provided so C callers get sane values without having to know them, and so
 * a zeroed struct is never mistaken for a valid request.
 */
struct LegeRenderOptions lege_render_options_default(void);

/**
 * Render one page and encode it, writing the file bytes into `out`.
 *
 * `cancellation` may be `NULL`. When non-null and cancelled, the call returns
 * [`LEGE_ERR_RENDER`] promptly rather than finishing the render.
 *
 * On success `out` owns a buffer the caller must release with
 * [`lege_buffer_free`]. On failure `out` is left empty.
 *
 * # Safety
 * `document` must be a valid open handle, `options` and `out` must be
 * non-null and writable, and `cancellation` must be null or a live token.
 */
int lege_document_render_page(const struct LegeDocument *document,
                              unsigned int page,
                              const struct LegeRenderOptions *options,
                              const struct LegeCancellation *cancellation,
                              struct LegeBuffer *out);

/**
 * Extract a page's text layer as UTF-8 into `out`, without a trailing NUL.
 *
 * A page with no text layer yields an empty buffer and [`LEGE_OK`]; that is
 * not an error, it is a scanned page.
 *
 * # Safety
 * `document` must be a valid open handle and `out` non-null and writable.
 */
int lege_document_page_text(const struct LegeDocument *document,
                            unsigned int page,
                            struct LegeBuffer *out);

/**
 * This library's version, as a static NUL-terminated string. Never null, and
 * must not be freed.
 */
const char *lege_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LEGE_RENDER_H */
